steps:
- name: maven:latest
  args: ['mvn', 'clean', 'install', '-D', 'skipTest']
- name: maven:latest
  args: ['mvn', 'test']
- name: node
  args: ['cd', 'jsproject']
  args: ['npm', 'install']
  args: ['npm', 'run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-project-id/myimage', '.']

