steps:
- name: maven:latest
  args: ['mvn', 'clean', 'install', '-D', 'skipTest']
- name: maven:latest
  args: ['mvn', 'test']
- name: node:latest
  args: ['npm', 'run']
  args: ['npm', 'build']
  args: ['echo', 'hey', 'node']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=jeanempe --password=9dd3bc56-319a-40a2-8a4e-8e74136ab21e']
  args: ['-c', 'docker build -t jeanempe/java-ci-cd .']
  args: ['-c', 'docker push jeanempe/java-ci-cd']
