steps:
- name: maven:latest
  args: ['mvn', 'clean', 'install', '-D', 'skipTest']
- name: maven:latest
  args: ['mvn', 'test']
- name: node:latest
  args: ['npm', 'run']
  args: ['npm', 'build']
  args: ['echo', 'hey', 'node']
- name: 'docker'
  entrypoint: 'docker'
  args: ['login', '-u', 'jeanempe','-p','9dd3bc56-319a-40a2-8a4e-8e74136ab21e']
  args: ['build', '-t', 'jeanempe/java-ci-cd:tagname', '.']
  args: ['push', 'jeanempe/java-ci-cd:tagname']
