steps:
- name: maven:latest
  args: ['mvn', 'clean', 'install', '-D', 'skipTest']
- name: maven:latest
  args: ['mvn', 'test']
- name: node:latest
  args: ['bash', '-c', 'cd jsproject']
  args: ['npm', 'run']
  args: ['npm', 'build']
  args: ['echo', 'hey', 'node']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=jeanempe --password=2d573c58-1eba-4cce-adb5-30f5ff22fcda']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t jeanempe/java-ci-cd .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push jeanempe/java-ci-cd']
  
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'cd jsproject']
  args: ['-c', 'docker build -t jeanempe/js-ci-cd .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'cd jsproject']
  args: ['-c', 'docker push jeanempe/js-ci-cd']
