steps:
- name: maven:latest
  args: ['mvn', 'clean', 'install', '-D', 'skipTest']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['mvn', 'test']
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['test']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-project-id/myimage', '.']

